// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertComponentController from "./alert_component_controller"
application.register("alert-component", AlertComponentController)

import CaptchaController from "./captcha_controller"
application.register("captcha", CaptchaController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ServersController from "./servers_controller"
application.register("servers", ServersController)
