require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.1.2
  NewCops: enable

# https://docs.rubocop.org/rubocop/cops_metrics.html
Metrics/MethodLength:
  Max: 30
  Exclude:
    - spec/**/*.rb

# https://docs.rubocop.org/rubocop/cops_lint.htm
Lint/MixedRegexpCaptureTypes:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/WordArray:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_layout.html
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_naming.html
Naming/BlockForwarding:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Naming/VariableNumber:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_bundler.html
Bundler/OrderedGems:
  Enabled: false

RSpec/BeEq:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 5
