require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 3.2.0
  NewCops: enable

# https://docs.rubocop.org/rubocop/cops_layout.html
Layout/ArrayAlignment:
  Enabled: false
Layout/EmptyLinesAroundExceptionHandlingKeywords:
  Enabled: false
Layout/HashAlignment:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/LineLength:
  Exclude:
    - config/initializers/devise.rb
  Max: 160
Layout/MultilineMethodCallBraceLayout:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideArrayPercentLiteral:
  Enabled: false
Layout/SpaceInsidePercentLiteralDelimiters:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_lint.html
Lint/DuplicateBranch:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_metrics.html
Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb
  Max: 40
Metrics/BlockLength:
  Exclude:
    - db/schema.rb
    - config/routes.rb
    - spec/**/*.rb
  Max: 60
Metrics/BlockNesting:
  Max: 5
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 20
Metrics/MethodLength:
  Exclude:
    - spec/**/*.rb
  Max: 80
Metrics/ParameterLists:
  Max: 6
  MaxOptionalParameters: 6
Metrics/PerceivedComplexity:
  Max: 30

# https://docs.rubocop.org/rubocop/cops_naming.html
Naming/AccessorMethodName:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/MethodParameterName:
  MinNameLength: 1
Naming/VariableNumber:
  Enabled: false

Rails/ActionOrder:
  Enabled: false
Rails/DynamicFindBy:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false

RSpec/BeEq:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ImplicitSubject:
  Enabled: false
RSpec/LetBeforeExamples:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Max: 5

# https://docs.rubocop.org/rubocop/cops_style.html
Style/BlockComments:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  Enabled: false
Style/TrailingCommaInHashLiteral:
  Enabled: false
Style/TrailingUnderscoreVariable:
  Enabled: false
Style/WordArray:
  Enabled: false
