test:
  adapter: test

development:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.5
  message_retention: 1.day

production:
  adapter: solid_cable
  connects_to:
    database:
      writing: cable
  polling_interval: 0.5
  message_retention: 1.day
