default: &default
  adapter:  postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool:     <%= ENV.fetch("DATABASE_POOL") { 5 } %>
  host:     <%= ENV.fetch("DATABASE_HOST") %>
  port:     <%= ENV.fetch("DATABASE_PORT") %>
  username: <%= ENV.fetch("DATABASE_USER") %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") %>

test:
  <<: *default
  database: web_app_test
  migrations_paths: db/migrate

development:
  primary:
    <<: *default
    database: web_app_development
    schema_dump: schema.rb
    migrations_paths: db/migrate
  queue:
    <<: *default
    database: web_app_development_queue
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: web_app_development_cache
    schema_dump: cache_schema.rb
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: web_app_development_cable
    schema_dump: cable_schema.rb
    migrations_paths: db/cable_migrate

production:
  primary:
    <<: *default
    database: web_app_production
    schema_dump: schema.rb
    migrations_paths: db/migrate
  queue:
    <<: *default
    database: web_app_production_queue
    schema_dump: queue_schema.rb
    migrations_paths: db/queue_migrate
  cache:
    <<: *default
    database: web_app_production_cache
    schema_dump: cache_schema.rb
    migrations_paths: db/cache_migrate
  cable:
    <<: *default
    database: web_app_production_cable
    schema_dump: cable_schema.rb
    migrations_paths: db/cable_migrate
