servers:
  web:
    - upper.town

ssh:
  keys:
    - "~/.ssh/app_ssh_key"
    - "~/.ssh/app-upper_town-production"

proxy:
  host: upper.town

env:
  clear:
    APP_ENV: production
    APP_HOST: upper.town
    NOREPLY_EMAIL: noreply@upper.town

builder:
  remote: ssh://app@upper.town

accessories:
  postgres:
    host: upper.town
