image: upper_town/web_app

service: web_app

servers:
  web:
    - sandbox.upper.town

ssh:
  user: app
  port: 22
  config: true
  keys_only: true
  keys:
    - "~/.ssh/app_ssh_key"
    - "~/.ssh/app-upper_town-sandbox"

proxy:
  ssl: true
  host: sandbox.upper.town
  response_timeout: 60
  healthcheck:
    interval: 5
    path: /up
    timeout: 60

registry:
  server: registry.gitlab.com
  username:
    - CI_REGISTRY_USER
  password:
    - CI_REGISTRY_PASSWORD

env:
  clear:
    APP_ENV: sandbox
    APP_HOST: sandbox.upper.town
    APP_PORT: 3000
    NOREPLY_EMAIL: noreply@sandbox.upper.town
    PERIODS_MIN_PAST_TIME: '2024-01-01T00:00:00Z'
    POSTGRES_HOST: web_app-postgres
    RAILS_ENV: production
    RAILS_MAX_THREADS: 5
  secret:
    - ACTIVE_RECORD_ENCRYPTION_DETERMINISTIC_KEY
    - ACTIVE_RECORD_ENCRYPTION_KEY_DERIVATION_SALT
    - ACTIVE_RECORD_ENCRYPTION_PRIMARY_KEY
    - ADMIN_AUTH_ROUTES_SALT
    - H_CAPTCHA_SECRET_KEY
    - H_CAPTCHA_SITE_KEY
    - POSTGRES_PASSWORD
    - POSTGRES_USER
    - RAILS_MASTER_KEY
    - SECRET_KEY_BASE
    - TOKEN_ADMIN_API_SESSION_SALT
    - TOKEN_ADMIN_SALT
    - TOKEN_ADMIN_SESSION_SALT
    - TOKEN_API_SESSION_SALT
    - TOKEN_SALT
    - TOKEN_SESSION_SALT

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  dbconsole: app exec --interactive --reuse "bin/rails dbconsole"

volumes:
  - /home/app/storage:/rails/storage

asset_path: /rails/public/assets

builder:
  arch: amd64
  local: false
  remote: ssh://app@sandbox.upper.town

accessories:
  postgres:
    image: postgres:17.2
    host: sandbox.upper.town
    port: '127.0.0.1:5432:5432' # POSTGRES_PORT
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_PASSWORD
    volumes:
      - /home/app/postgres:/var/lib/postgresql/data
