development:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: "*"
      processes: 1
      threads: 1
      polling_interval: 0.1

production:
  dispatchers:
    - polling_interval: 1
      batch_size: 500
  workers:
    - queues: ["critical", "default", "low"]
      processes: 1
      threads: 2
      polling_interval: 0.1
    - queues: ["default", "critical", "low"]
      processes: 1
      threads: 2
      polling_interval: 0.1
    - queues: ["low", "critical", "default"]
      processes: 1
      threads: 1
      polling_interval: 0.1
