development:
  dispatchers:
    - polling_interval: 1
  workers:
    - queues: ["critical", "default", "low"]
      polling_interval: 1

production:
  dispatchers:
    - polling_interval: 1
  workers:
    - queues: ["critical", "default", "low"]
      polling_interval: 1
    - queues: ["default", "critical", "low"]
      polling_interval: 1
    - queues: ["low", "critical", "default"]
      polling_interval: 1
