webhooks_publisher_job:
  class: Webhooks::PublisherJob
  schedule: "*/5 * * * * *"

servers_stats_consolidator_job:
  class: Servers::StatsConsolidatorJob
  schedule: "* * * * *"

servers_stats_previous_consolidator_job_week:
  class: Servers::StatsPreviousConsolidatorJob
  schedule: "15 0 * * 1"
  args: ["week"]

servers_stats_previous_consolidator_job_month:
  class: Servers::StatsPreviousConsolidatorJob
  schedule: "30 0 1 * *"
  args: ["month"]

servers_stats_previous_consolidator_job_year:
  class: Servers::StatsPreviousConsolidatorJob
  schedule: "45 0 1 1 *"
  args: ["year"]

servers_verifier_job:
  class: Servers::VerifierJob
  schedule: "0 2 * * *"

clear_solid_queue_finished_jobs:
  command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.5)"
  schedule: "15 * * * *"

servers_delete_archived_without_votes_job:
  class: Servers::DeleteArchivedWithoutVotesJob
  schedule: "0 3 * * *"

servers_delete_marked_for_deletion_job:
  class: Servers::DeleteMarkedForDeletionJob
  schedule: "15 3 * * *"

delete_expired_tokens_job:
  class: DeleteExpiredTokensJob
  schedule: "30 3 * * *"

webhooks_delete_old_events_job:
  class: Webhooks::DeleteOldEventsJob
  schedule: "45 3 * * *"
