# production:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day


# TODO: define these jobs

# servers_consolidate_vote_counts_scheduler_job_current:
#   cron: "0 1 * * *"
#   class: Servers::ConsolidateVoteCountsSchedulerJob
#   args: ["current"]
#   queue: default

# servers_consolidate_vote_counts_scheduler_job_all:
#   cron: "0 1 1 * *"
#   class: Servers::ConsolidateVoteCountsSchedulerJob
#   args: ["all"]
#   queue: default

# servers_consolidate_rankings_scheduler_job_current:
#   cron: "0 2 * * *"
#   class: Servers::ConsolidateRankingsSchedulerJob
#   args: ["current"]
#   queue: default

# servers_consolidate_rankings_scheduler_job_all:
#   cron: "0 2 1 * *"
#   class: Servers::ConsolidateRankingsSchedulerJob
#   args: ["all"]
#   queue: default

# servers_verify_scheduler_job:
#   cron: "0 3 * * *"
#   class: Servers::VerifySchedulerJob
#   args: []
#   queue: default

# servers_delete_archived_without_votes_job:
#   cron: "0 5 * * *"
#   class: Servers::DeleteArchivedWithoutVotesJob
#   args: []
#   queue: default

# servers_delete_marked_for_deletion_job:
#   cron: "0 6 * * *"
#   class: Servers::DeleteMarkedForDeletionJob
#   args: []
#   queue: default

# server_webhooks_delete_old_events_job:
#   cron: "0 4 * * *"
#   class: ServerWebhooks::DeleteOldEventsJob
#   args: []
#   queue: default

# delete_expired_tokens_job:
#   cron: "0 5 * * *"
#   class: DeleteExpiredTokensJob
#   args: []
#   queue: default

# server_banner_image_cache_store_clean_up_job:
#   cron: "*/30 * * * *"
#   class: ServerBannerImageCacheStoreCleanUpJob
#   args: []
#   queue: default
