# For kredis gem

production:
  url: <%= "redis://#{ENV.fetch('REDIS_HOST')}:#{ENV.fetch('REDIS_PORT')}/#{ENV.fetch('REDIS_CACHE_DB')}" %>
  timeout: 1

development:
  url: <%= "redis://#{ENV.fetch('REDIS_HOST')}:#{ENV.fetch('REDIS_PORT')}/#{ENV.fetch('REDIS_CACHE_DB')}" %>
  timeout: 1

test:
  url: <%= "redis://#{ENV.fetch('REDIS_HOST')}:#{ENV.fetch('REDIS_PORT')}/#{ENV.fetch('REDIS_CACHE_DB')}" %>
  timeout: 1
