production:
  url: <%= ENV.fetch('REDIS_CACHE_URL') %>
  timeout: 1

development:
  url: <%= ENV.fetch('REDIS_CACHE_URL') %>
  timeout: 1

test:
  url: <%= ENV.fetch('REDIS_CACHE_URL') %>
  timeout: 1
